---
# tasks file for apache
- name: install apache
  yum: 
    name: httpd
    state: installed
- name: start apache service
  service:
    name: httpd   
    state: started
- name: create index file
  file: 
    path: /var/www/html/index.html
    state: touch
- name: editing index.html file
  lineinfile: 
    path: /var/www/html/index.html
    line: "I am ansible master\nI never give up"
  notify: restart apache 
 
