---
- hosts: localhost
  become: true
  connection: ssh
  gather_facts: yes
  tasks: 
    - name: Install apache on ubuntu
      apt: name=apache2 state=latest
      when: ansible_os_family == "Debian"

    - name: Install apache on ubuntu
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"

    - name: start apache service
      service: name=apache2 state=started
      when: ansible_os_family == "Debian"
    
    - name: start apache service on Redhat
      service: name=httpd state=started
      when: ansible_os_family == "RedHat"
      notify: apache restart

    - name: Create index file
      file: 
        path: /var/www/html/index.html
        state: touch
    
    - name: make entry into it 
      lineinfile: 
        path: /var/www/html/index.html
        line: "BHUSHAN WEBSITE"

  handlers: 
    - name: apache restart 
      service: name=httpd state=restarted
    

     
