- hosts: localhost
  become: true
  tasks: 
    - name: Install Docker 
      yum: 
        name: docker-io
        state: installed
      async: 500
      poll: 0
      register: my_task
   
    - debug: msg={{ my_task }}

    - name: get the task status using ansible async_status
      async_status: 
        jid: "{{ my_task.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 30
