---
- name: trigger
  hosts: localhost
  vars: 
    Uname: "bhushan" 
    Pass: "ganesha"
    HostName: "18.221.193.77:8080"
    TokenName: "11e1727056b797c26438ea75abd8676d5f"
  tasks: 
    - name: Queue build
      uri:
        url: "http://{{ HostName }}/job/{{ JobName }}/build?token={{ TokenName }}"
        method: POST
        user: "{{ Uname }}"
        password: "{{ Pass }}" 
        force_basic_auth: yes
        status_code: 201
    
      
