---
- hosts: localhost
  become: yes
  user: ansible
  vars: 
    kernel_v: "{{ ansible_version }}"
  tasks:
    - name: get kernel version
      shell: uname -r | grep '^[0-9]*\.[0-9]*' -o
      #shell: uname -r | awk -F"." '{print $6}'
      register: prepatch_kernel

    - debug: msg="{{prepatch_kernel.stdout}}"

    - name: Add cstate and reboot bios if kernel is 4.8
      shell: echo "Do what you need to do"
      when: prepatch_kernel.stdout == "4.8"

    - name: Run check list 
      script: /home/ansible/ansible/playbooks/checklist.sh

    - name: Patch the OS and kernel 
      yum: 
        name: '*'
        state: latest
        exclude: kernel*
        
    - name: get kernel version
      shell: uname -r | grep '^[0-9]*\.[0-9]*' -o
      #shell: uname -r | awk -F"." '{print $6}'
      register: postpatch_kernel

    - debug: msg="{{postpatch_kernel.stdout}}"

    - name: Add cstate and reboot bios if kernel is 4.8
      shell: echo "Do what you need to do"
      when: postpatch_kernel.stdout == "4.8"

