---
- hosts: apache
  sudo: yes
  connection: ssh
  tasks: 
  - name: installed apache web server
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"
  - name: start the apache service
    service: name=httpd state=started
    
