---
- hosts: docker
  become: true
  tasks:
    - name: login into docke hub registry
      docker_login:
        email: "bmahajan0@gmail.com"
        username: "bmahajan"
        password: "ganesha@123"
    - name: launch container  
      docker_container: 
        name: splunksh
        state: started
        image: "bmahajan/splunksh:v2"
        pull: true
        detach: yes
        tty: yes
        ports: 
          - "8000:8000"
