---
- hosts: doc
  strategy: debug
  become: true
  vars: 
    hip: "{{ hipinside }}"
  tasks:
    - name: login into docke hub registry
      docker_login:
        email: "bmahajan0@gmail.com"
        username: "bmahajan"
        password: "{{ paswd }}"

    - name: launch container App1 
      docker_container: 
        name: app1
        state: started
        image: "bmahajan/lb:app1"
        pull: true
        detach: yes
        tty: yes
        ports: 
          - "8081:80"
    - name: Integrate RDS with PHP
      shell: docker exec app1  sed -i 's/127.0.0.1/gymsystemdb.czrdtrac0wnc.us-east-2.rds.amazonaws.com/g; s/root/bhushan/g; s/""/"ganesha123"/g'  /opt/lampp/htdocs/gym_management_system/includes/db_connect.php 

    - name: Name to home page
      shell: docker exec app1 sed -i '5i\<li>App1</li>\ ' /opt/lampp/htdocs/gym_management_system/includes/footer.php



    - name: launch container App2 
      docker_container:
        name: app2
        state: started
        image: "bmahajan/lb:app2"
        pull: true
        detach: yes
        tty: yes
        ports:
          - "8082:80"
    - name: Integrate RDS with PHP
      shell: docker exec app1  sed -i 's/127.0.0.1/gymsystemdb.czrdtrac0wnc.us-east-2.rds.amazonaws.com/g; s/root/bhushan/g; s/""/"ganesha123"/g'  /opt/lampp/htdocs/gym_management_system/includes/db_connect.php

    - name: Name to home page
      shell: docker exec app1 sed -i '5i\<li>App2</li>\ ' /opt/lampp/htdocs/gym_management_system/includes/footer.php


    - name: starting the all services of containers manually
      command: docker exec "{{ item }}" /opt/lampp/lampp start
      with_items: 
        - app1
        - app2
      ignore_errors: yes
   
    - name: launch container nginx  
      docker_container:
        name: nginx
        state: started
        image: "bmahajan/lb:nginx"
        pull: true
        detach: yes
        tty: yes
        ports:
          - "80:80"

     
    - name: check existing IP in nginx conf file
      shell: docker exec nginx grep [0-9] /etc/nginx/nginx.conf | head -2 | tail -1 | awk -F ":" '{print $1}'| awk -F " " '{print $2}'
      register: ext_ip
    - debug: 
        var: ext_ip
    - name: Configure Nginx
      #shell: docker exec nginx sed  -i -e 's/3.17.60.70\b/{{ hip }}/g' /etc/nginx/nginx.conf
      shell: docker exec nginx sed  -i -e 's/{{ item }}\b/{{ hip }}/g' /etc/nginx/nginx.conf
      with_items:
        - "{{ ext_ip.stdout }}"
     
      
   # - name: start nginx service 
    #  shell: docker exec nginx /etc/init.d/nginx start 
     # register: ngstart
#    - debug: 
 #       var: ngstart
