---
- hosts: "{{ instance }}"
  become: true
  tasks:
    - name: login into docke hub registry
      docker_login:
        email: "bmahajan0@gmail.com"
        username: "bmahajan"
        password: "{{ paswd }}"

    - name: launch container1
      docker_container: 
        name: xampplb1
        state: started
        image: "bmahajan/gym_management_system:v1"
        pull: true
        detach: yes
        tty: yes
        volumes: 
          - "/gym_mgmt_system:/gym_mgmt_data"
        ports: 
          - "8081:80"
          - "8082:3306"

