---
- hosts: "{{ instance }}"
  become: true
  tasks:
    - name: start container on docker1/2 server
      docker_container: 
        name: xampplb1
        image: bmahajan/gym_management_system:v2
        state: started
        name: xampplb2
        image: bmahajan/gym_management_system:v2
        state: started
      tags: start
      
    - name: Stop container on docker1/2 server
      docker_container: 
        name: xampplb1
        image: bmahajan/gym_management_system:v2
        state: stopped
        name: xampplb2
        image: bmahajan/gym_management_system:v2
        state: stopped
      tags: stop
