---
- hosts: ec2
  gather_facts: no
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: Attache EBS volume  
      ec2_vol: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance: i-06d538d72ea1fdd82 
        id: vol-071f98cea98596648 
        delete_on_termination: yes
