---
- name: ec2 launcher
  hosts: localhost
  connection: local
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: launching ec2
      ec2_instance_facts: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        region: us-east-1
      register: output  
    - name: Display instance list
      debug: 
        var: output.instances
    
