---
- hosts: ec2
  gather_facts: no
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: Gather tags
      ec2_tag:  
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: list
        resource: i-0b39690d6838ba242
      register: tags

    - name: Display tags
      debug: 
        var: tags.tags
    - name: Add tags to resource
      ec2_tag: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        resource: snap-0ea379bde165a6c5d
        tags: 
          system: ERP
          version: 1.2
        state: present
