---
- hosts: ec2
  gather_facts: no
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: launching ec2
      ec2_ami_facts:  
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          description: "*redhat*"
      register: ami_facts
    - name: Output information
      debug: 
        msg: "{{ item.description }}"
      loop_control: 
        label: "{{ item.image_id }}"
      loop: "{{ ami_facts.images }}"
      
