---
- hosts: ec2
  gather_facts: no
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: launching ec2
      ec2_ami:  
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-0d9f14116d1b3466f 
        name: MyNewAMI
        state: present
