---
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
#   gather_facts: False
    become: true
    tasks:
      - name: list current running instance ID
        shell: sudo aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters Name=instance-state-name,Values=running --output text
        register: instance_id

      - debug: var=instance_id.stdout
        
      - name: Stop ec2 Instance
        ec2:
          instance_ids: "{{ instance_id.stdout }}"
          key_name: aws_final
          region: us-east-2
          vpc_subnet_id: subnet-052af449
          assign_public_ip: yes
          wait: yes
          state: stopped
        tags: shut
      
      - name: Start EC2 Instance
        ec2:
          instance_ids: "{{ instance_id.stdout }}"
          key_name: aws_final
          region: us-east-2
          vpc_subnet_id: subnet-052af449
          assign_public_ip: yes
          wait: yes
          state: running
        tags: run

      - name: Destroying EC2 Instance
        ec2:
          instance_ids: "{{ instance_id.stdout }}"
          key_name: aws_final
          region: us-east-2
          vpc_subnet_id: subnet-052af449
          assign_public_ip: yes
          wait: yes
          volumes:       
              device_name: /dev/sda1
              delete_on_termination: true
          state: absent
        tags: rm
        register: stat
      - debug: var=stat.stdout
        
        
