---
- name: ec2 launcher
  hosts: localhost
  become: true
  connection: local
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: Create key 
      ec2_key:    
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: ganesha_key
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"   

    - name: Launch ec2 instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        key_name: ganesha_key
        image: ami-0b69ea66ff7391e80
        user_data: "{{ lookup('file', '/home/ansible/ansible/playbooks/ans_env.sh')}}" 
        group: ASGSG
        vpc_subnet_id: subnet-8b371aec
        assign_public_ip: yes
        wait: yes
        count: 1
        instance_tags:
          app: Docker1
      register: ec2

    - name: Create SSH Group to login dynamically to EC2 Instance
      lineinfile: dest=/etc/ansible/hosts
                  regexp={{ item.public_ip }}
                  insertafter="[webgroup]"
                  line={{ item.public_ip }}
                  state=present
      with_items: "{{ ec2.instances }}"
         
    - name: Wait for SSH to come up
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22  
                    state=started
      with_items: "{{ ec2.instances }}"
        


       
