---
- name: Provision VPC 
  hosts: localhost
  become: true
  vars: 
    my_region: us-east-2
  tasks: 
    ec2_vpc: 
      state: present
      cidr_block: 10.0.0.0/16
      resource_tags: { "Environment": "Analytics" }
      region: "{{ my_region }}"
    register: vpc
      subnets: 
        - cidr: 10.0.1.0/28
          az: us-east-2a
          resource_tags: { "Environment" : "private-subnet" }
      internet_gateway: true
      route_tables: 
        - subnets: 
            - 10.0.1.0/28

- name: Provision EC2 instance
  hosts: localhost
  connection: local
  become: true
  tasks: 
    name: Launch the new ec2 instance
    ec2: 
      instance_type: t2.micro
      key_name: aws_final
      image: ami-0f2b4fc905b0bd1f1
      user_data: "{{ lookup('file', '/home/ansible/ansible/playbooks/ans_env.sh')}}"
      region: "{{ my_region }}"
      group: Newsc
      vpc_subnet_id: vpc.
