---
- name: ec2 launcher
  hosts: localhost
  connection: local
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: Get Subnet ID from existing server 
      ec2_instance_facts: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        filters: 
          tag:Name: Leo
      register: ec2_facts

    - name: Stop Leo instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags: 
          Name: Leo

    - name: Deploy new EC2 instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        key_name: myasgkey
        image: ami-0b69ea66ff7391e80    
        group: ASGSG
        vpc_subnet_id: "{{ ec2_facts.instances[0].image_id }}" 
        assign_public_ip: yes
        
