---
- name: Delete instances
  hosts: localhost
  connection: local
  become: yes

  vars:
    service_account_email: 524495382084-compute@developer.gserviceaccount.com
    credentials_file: /home/centos/static-groove-225809-b8af1b5ce15e.json
    project_id: static-groove-225809
    zone: us-east1-b    
    machine_type: n1-standard-1

  tasks:
    - name: Destroy instances
      gce:
        instance_names: "{{ instances }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        disk_auto_delete: true
        preemptible: true
        state: absent
