---
- name: Delete instances
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    service_account_email: 524495382084-compute@developer.gserviceaccount.com
    credentials_file: /home/centos/static-groove-225809-b8af1b5ce15e.json
    project_id: static-groove-225809
    zone: us-central1-a

  tasks:
    - name: Destroy instances
      gce:
        instance_names: "{{ instances }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: present
