---
- hosts: local
  become: yes
  tasks: 
    - name: Ensure apache is installed
      yum: 
        name: httpd
        state: latest

    - name: start httpd service
      service: 
        name: httpd
        state: started

    - name:  Create index file
      file: 
        path: /var/www/html/index.html
        state: touch


    - name: Insert data into index file
      lineinfile: 
        path: /var/www/html/index.html
        line: "new data"
      notify: start apache 
   
  handlers: 
    - name: start apache
      service: name=httpd state=restarted
    
        
    
