---
- hosts: doc
  become: true
  gather_facts: no
  tasks:
    - name: Install JDK
      yum:
        name: java-1.8.0-openjdk-devel*
        state: latest

    - name: Set ENV JAVA var
      shell: echo "{{ item }}" >> /root/.bashrc
      with_items: 
        - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64
        - PATH=$PATH:$JAVA_HOME:$HOME/bin

    - name: Add repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: 0644

    - name: Add GPG key 
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install jenkins on centos7
      yum: name=jenkins state=latest

    - name: Start and enable Jenkins service
      service: name=jenkins state=started enabled=yes
      register: stat

    - name: show the status of the service
      debug: var=stat.stdout

     
  
