---
- hosts: doc
  become: true
  gather_facts: no
  tasks:
    - include: jdk_install_tar_task.yml

    - name: Add repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: 0644

    - name: Add GPG key 
      shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install jenkins on centos7
      yum: name=jenkins state=latest

    - name: Start and enable Jenkins service
      service: name=jenkins state=started enabled=yes
      register: stat

    - name: show the status of the service
      debug: var=stat.stdout

     
  
