---
    - name: Download jdk
      get_url: 
        url: http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_linux-x64_bin.rpm
        headers:  "Cookie: oraclelicense=accept-securebackup-cookie"
        dest: /opt/jdk-11.0.2_linux-x64_bin.rpm

    - name: Install JDK
      yum: 
        name: /opt/jdk-11.0.2_linux-x64_bin.rpm
        state: present
    
    - name: Upgrade JDK
      shell: rpm -Uvh /opt/jdk-11.0.2_linux-x64_bin.rpm
      ignore_errors: yes

    - name: Set JAVA ENV
      shell: echo "export JAVA_HOME=/usr/java/jdk-11.0.2" >> /etc/profile
