---
- hosts: doc
  become: true
  gather_facts: no
  tasks: 
    - name: Download jdk
      get_url:
        url: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        dest: /tmp/jdk-8u201-linux-x64.tar.gz
    - name: Extract the jdk file 
      shell: tar -xvf /tmp/jdk-8u201-linux-x64.tar.gz -C /opt
      
    - name: Set ENV variable
      shell: 'for f in `ls /opt/jdk-8u201/bin`; do update-alternatives --install "/usr/bin/${f}" "${f}" "/opt/jdk-8u201/bin/${f}" 1; done'
    - name: Update java alertive using bash script
      script: /home/ansible/ansible/playbooks/java_update_alt.sh --some-argument -8u201

    - name: ENV VAR JAVA
      shell: echo "{{ item }}" >> /root/.bash_profile
      with_items:
        - export JAVA_HOME=/opt/jdk-8u201/bin
        - export JRE_HOME=/opt/jdk-8u201/jre
        - export PATH=$PATH:/opt/jdk-8u201/bin:/opt/jdk-8u201/jre/bin
        
        
        
