---
- hosts: doc
  become: true
  gather_facts: no
  tasks: 
    - name: Download jdk
      get_url: 
        url: http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_linux-x64_bin.tar.gz
        #headers:  "Cookie: oraclelicense=accept-securebackup-cookie"
        dest: /opt/jdk-9.0.4_linux-x64_bin.tar.gz
      
    - name: Extract the JDK file 
      unarchive: src=/opt/jdk-9.0.4_linux-x64_bin.tar.gz dest=/opt/ remote_src=true
     
