---
- hosts: doc
  become: true
  gather_facts: no
  tasks: 
    - name: Download jdk
      get_url: 
        url: http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_linux-x64_bin.tar.gz
        #headers:  "Cookie: oraclelicense=accept-securebackup-cookie"
        dest: /tmp/jdk-9.0.4_linux-x64_bin.tar.gz

    - name: Unarchive and Install JDK
      unarchive:  
        src: /tmp/jdk-9.0.4_linux-x64_bin.tar.gz
        dest: /opt/
        #extra_opts:  ["--use-compress-program=pbzip2","--exclude=data/tmp"]
        remote_src: yes
