--- ## LOOKUP PLAYBOOK EXAMPLE
- hosts: apache
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:   
    - debug: msg="Lookup the SuperHero for BRUCE WAYNE {{ lookup('csvfile', 'Bruce Wayne file=lookup.csv delimiter=, default=NOMATCH') }}" 
