---
- hosts: localhost
  become: true
  gather_facts: no
  tasks:
   - name: Download MySQL rpm
     yum:    
       name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
       state: present
  
   - name: Install MySQL
     yum: 
       name: "{{ item }}" 
       state: latest 
     with_items: 
       - mysql-server
       - MySQL-python       
  
   - name: Start MySQL service
     service: 
       name: mysqld
       state: started
       enabled: yes
  

   - name: Create databse 
     mysql_db:
       name: gym_management_system
       state: present

   - name: import DB to MySQL
     mysql_db: 
       state: import
       name: gym_management_system 
       target: gym_management_system.sql
        
    
