---
- hosts: master
  gather_facts: true
  remote_user: ansible
  vars: 
    ssh_keys: '/home/ansible/.ssh/id_rsa.pub'
  tasks: 
    - name: copy ssh key
      authorized_key: 
        user: ansible
        manage_dir: true
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present
      delegate_to: "{{ item }}"
      with_items: 
        - node1
        - node2

  
