---
- hosts: all
  gather_facts: true
  become: true #remote_user: ansible
  #vars: 
  #  ssh_keys: '/home/ansible/.ssh/id_rsa.pub'
  tasks: 
    - name: create a user
      user: 
        name: poonam
        state: present
    - name: copy ssh key
      authorized_key: 
        user: poonam
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present
      delegate_to: "{{ item }}"
      with_items: 
        - client1
        - client2

  
