---
- hosts: localhost
  become: true
  tasks: 
    - name: Install Python3 dependant packages
      yum: 
        name: "{{ item }}"
        state: installed
      with_items: 
        - gcc
        - openssl-devel
        - bzip2-devel
   
     - name: Download Python3 
       get_url: 
         url: https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
         path: /tmp
      
     - name: Extract tar file
       unarchive: 
         src: /tmp/Python-3.7.2.tgz
         dest: /usr/src
         
        
