- name: Configure RDS 
  hosts: localhost
  become: true
  tasks: 
  gather_facts: false
    - name: Provision RDS 
      rds: 
        command: create
        db_engine: MySQL
        allocated_storage: 10
        instance_type: db.t2.micro 
        username: bhushan
        password: ganesha123
        security_groups: Newsc
        db_name: gym_management_system
        port: 3306
        publicly_accessible: yes
        wait: yes
        wait_timeout: 300
        instance_name: gymdb
      register: gymdb

    - name: Add new instance to host group
      shell: echo "{{ item.endpoint }}" >> rds-hostname.txt 
      add_host: hostname={{ item.endpoint }} groups=database     
      with_items: "{{ gymdb.instance }}"
      

