- name: Provisioning RDS MySql DB
  hosts: localhost
  become: true
  tasks: 
    - rds: 
        command: create
        instance_name: gym_system
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro 
        username: bhushan
        password: ganesha123
        security_groups: Newsc
        db_name: gym_management_system
        port: 3306
        publicly_accessible: yes
        wait: yes
        wait_timeout: 300
        
