---
- hosts: localhost
  become: true
  tasks:
    - name: Check string in file 
      replace:  
        path: /usr/lib/sysctl.d/50-default.conf
        regexp: 'net.ipv4.conf.all.rp_filter = 1'
        replace: "net.ipv4.conf.all.rp_filter = 2"
        backup: yes
