---
- hosts: localhost
  become: true
  connection: local
  vars: 
    bucketname: abhiwing
  tasks:
    - name: Checking S3 bucket size
     #shell:  s3cmd la  --recursive  --human-readable
      shell:  s3cmd la  --recursive  --human-readable | awk -F " " '{print $4,"",$3}' | perl -i -n -e "print if /s/"
      register: disk_space 
   
    - name: Displaying disk space
      debug:
        msg: "{{ disk_space.stdout }}"
 
    - local_action: 
            module: copy
            content: "{{ disk_space.stdout }}"
            dest: /tmp/s3space_{{ ansible_date_time.date }}.txt
        
    - name: Display file
      shell: cat /tmp/s3space_{{ ansible_date_time.date }}.txt
      register: dpf

    - name: Send an email and attachment
      mail: 
        to: bmahajan0@gmail.com
        cc: rajendrakumars52@gmail.com
        subject: AWS S3 bucket space utilizion    
        body: "{{ dpf.stdout }}"
       #attach: /tmp/s3space_{{ ansible_date_time.date }}.txt
      delegate_to: localhost
   

