---
- hosts: local
  become: true
  serial: # Execute command on all hosts at a time or parallaly
     - 1
 #   - 2 
#    - 50% 
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: latest

    - name: Start and enable the service
      service: 
        name: httpd
        state: started
       # enabled: yes
    - name: Create index file
      file: 
        path: /var/www/html/index.html
        state: touch

    - name: Add line to index.html
      lineinfile: 
        path: /var/www/html/index.html
        line: "<html><head> MY SONE IS REYASNSH</head></html>"
