---
- hosts: master
  #user: ansible
  #sudo: yes
  connection: ssh
  gather_facts: yes
  vars: 
    playbook_version: 0.1
  tasks: 
    - name: Local Variable Display
      set_fact:
        myVar: Ansible_Geek
    - debug: msg={{ playbook_version }}   
    - debug: msg={{ myVar }}
  
    - name: Bring private ip of remote server
      set_fact: 
        privateip: "{{ ansible_all_ipv4_addresses  }}"
    
    - debug: msg={{ privateip }}

  
