---
- hosts: webservers
  sudo: yes
  gather_facts: no
  tasks: 
    - name: ensure apache is at the latest version
      yum: name=httpd state=latest
    - name: service should be started
      service: name=httpd state=started

- hosts: databases
  sudo: yes
  tasks: 
    - name: ensure postgress is at the latest version
      yum: name=postgresql state=latest
    - name: ensure postgresql service started
      service: name=postgresql state=started
