---
- hosts: apache
  sudo: yes
  connection: ssh
  gather_facts: no  
  user: ansible
  tasks: 
    - name: Does a file in a path exist or not ?     
      stat: path=/home/ansible/abc
      register: p
    - debug: msg="The path exists and is directory"
      when: p.stat.isdir is defined and p.stat.isdir
