--- ## Until example
- hosts: apache
  sudo: yes
  connection: ssh
  user: ansible
  gather_facts: no
  tasks: 
    - name: Installing apache
      yum: pkg=httpd state=latest
    - name: Verify service status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1 ## loop run till find error/failed
      retries: 5
      delay: 5
    - debug: var=result
   
      
  
