---
- name: Create security group 
  hosts: localhost
  connection: local
  vars_files: 
    - /home/ansible/ansible/playbooks/keys.yml
  tasks:
    - name: Get Subnet ID from existing server 
      ec2_vpc_net_facts: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
      register: vpc_facts
    - debug: 
        var: vpc_facts
