---
- hosts: all
  sudo: yes
  gather_facts: no
  user: ansible
  tasks: 
    - name: Install apache tomcat 
      action: yum name=httpd state=present
    - name: waiting for port 80 to listen
      wait_for:
        port: 80
        state: started
