---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache server
      yum:
         name: httpd 
         state: latest
    - name: start apache service
      service: 
        name: httpd 
        state: started
    - name: create index file 
      file: 
        path: /var/www/html/index.html
        state: touch
    - name: add line to index file
      lineinfile:
        path: /var/www/html/index.html 
        line: "ABHI THE BAHUBALI"
        
